write(['1 <', '1 !', '2 DOCTYPE','3  html','1 >']);
write(['1 <', '2 html', '3  lang','1 =','4 "en"', '1 >']);
write(["t 1"]);
write(['1 <', '2 head', '1 >']);
write(["t 1",'1 <', '2 meta', '3  charset', '1 =', '4 "UTF-8"', '1 >']);
write(["t 1",'1 <', '2 title', '1  >', '5 Desktop', '1 <', '2 /title', '1 >']);
write(['1 <', '1 /', '2 head', '1 >']);
write(["t 1"]);
write(['1 <', '2 body', '1 >']);
write(["t 1",'1 <', '2 div ', '3 id', '1 =', '4 "Content"', '1 >', '1 <', '2 /div', '1 >']);
write(['1 <', '1 /', '2 body', '1 >']);
write(['1 <', '1 /', '2 html', '1 >']);
write(["t 1"]);
write(['1 <', '2 script', '1 >']);
write(['t 1', '5 document', '3 .getElementById', '6 (', '4 "Content"', '6 )', '3 .', '5 innerHTML', '7  = ','4 "/Desktop.html"', '5 ;']);
write(['1 <', '1 /', '2 script', '1 >']);